### ISSUE TITLE
Support for custom API URLs

### ISSUE THREAD

**Issue by muety** [bokub/wakatime-to-toggl#5]
In order to support alternative WakaTime-compatible backends like [wakapi](https://github.com/muety/wakapi) (disclaimer: I am the author), it would be cool to be able to configure a custom API URL other than `https://wakatime.com/api`.

**Comment by bokub** [comment]
I had no idea this existed!

However, what would be the use case? Exporting wakapi data to toggl?

**Comment by muety** [comment]
Exactly!

**Comment by bokub** [comment]
Are there any other WakaTime-compatible backends like wakapi, or is it the only one?

Do you want to make a PR, or would your prefer if I made it myself?

**Comment by muety** [comment]
> Are there any other WakaTime-compatible backends

Yes, there is also [hakatime](https://github.com/mujx/hakatime).

> Do you want to make a PR, or would your prefer if I made it myself?

I'll do a PR!

**Comment by muety** [comment]
I just realized that this requires a change in Wakapi first: https://github.com/muety/wakapi/issues/261.
Wakapi does not yet implement the `durations` endpoint, but will in the future. I'll keep this issue open and come back to it once everything's set on Wakapi's site.
